In [44]:
import numpy as np
from random import randint

# Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;  
   Операции произведения не определены
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;  
   Определена операция $AB$, рамерность итоговой матрицы - $2 \times 3$
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;  
   Определены операции $AB, BA$, рамерность итоговых матриц - $8 \times 8$ и $3 \times 3$ соответственно
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.  
   Определены операции $AB, BA$, рамерность итоговых матриц - $4 \times 4$
   
    

___

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B = \begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix} + \begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix} = 
\begin{pmatrix} 1+4 & -2+(-1)\\ 3+0 & 0+5 \end{pmatrix} = \begin{pmatrix} 5 & -3\\ 3 & 5 \end{pmatrix}$  

$A \cdot B = \begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix} \cdot \begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix} = 
\begin{pmatrix} 1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1)+ (-2) \cdot 5\\ 3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5 \end{pmatrix} = \begin{pmatrix} 4 & -11\\ 12 & -3 \end{pmatrix}$

$B \cdot A =  \begin{pmatrix} 4 & -1\\ 0 & 5 \end{pmatrix} \cdot \begin{pmatrix} 1 & -2\\ 3 & 0 \end{pmatrix} = 
\begin{pmatrix} 
4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2)+ (-1) \cdot 0 \\ 
0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 0 
\end{pmatrix} = 
\begin{pmatrix} 
1 & -8\\ 
15 & 0 
\end{pmatrix}$


In [2]:
a = np.array([1, -2, 3, 0]).reshape(2, 2)
b = np.array([4, -1, 0, 5]).reshape(2, 2)
a+b, a @ b, b @ a

(array([[ 5, -3],
        [ 3,  5]]),
 array([[  4, -11],
        [ 12,  -3]]),
 array([[ 1, -8],
        [15,  0]]))

___

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

$ 3A-2B+4C = 
3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} 
-2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}
+4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} 
+ \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}
+ \begin{pmatrix}
9 & -16\\ 
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$



In [3]:
a = np.array([1, 7, 3, -6]).reshape(2, 2)
b = np.array([0, 5, 2, -1]).reshape(2, 2)
c = np.array([2, -4, 1, 1]).reshape(2, 2)
3 * a - 2 * b + 4 * c

array([[ 11,  -5],
       [  9, -12]])

___

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.  



$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$  

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$  

$ AA^T = \begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} \cdot \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix}  = 
\begin{pmatrix} 
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3 \\ 
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3 \\
\end{pmatrix} = 
\begin{pmatrix} 
17 & 18 & 11 \\ 
18 & 29 & 4 \\ 
11 & 4 & 13 \\
\end{pmatrix}$

$ A^TA = \begin{pmatrix} 4 & 5 & 2\\ 1 & -2 & 3 \end{pmatrix} \cdot \begin{pmatrix}4 & 1\\ 5 & -2\\ 2 & 3 \end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3 \\ 
\end{pmatrix} = 
\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\ 
\end{pmatrix}$

In [4]:
a = np.array([4, 1, 5, -2, 2, 3]).reshape(3, 2)
a @ a.T, a.T @ a

(array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

___

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [68]:
def mul_mx(mx_1, mx_2):
    if len(mx_1) != len(mx_2[0]):
        return None
    part = []
    result = []
    cm_sm = 0
    for i in range(len(mx_1)):
        for j in range(len(mx_2[0])):
            for k in range(len(mx_1[0])):
                cm_sm += mx_1[i][k] * mx_2[k][j]
            part.append(cm_sm)
            cm_sm = 0
        result.append(part.copy())
        part.clear()
    return result    

In [69]:
m, n = 4, 5
make_mx = lambda x, y: [[randint(-10, 10) for _j in range(y)] 
                        for _i in range(x)]
c, d = make_mx(m, n), make_mx(n, m)
c_n, d_n = np.array(c).reshape(m, n), np.array(d).reshape(n, m)
print(mul_mx(d, c))
print(d_n @ c_n)

[[-134, 132, -10, -76, 86], [115, 58, 51, 12, -23], [41, -50, 10, -49, -61], [32, 99, -35, 13, 1], [-65, 23, 31, -8, 60]]
[[-134  132  -10  -76   86]
 [ 115   58   51   12  -23]
 [  41  -50   10  -49  -61]
 [  32   99  -35   13    1]
 [ -65   23   31   -8   60]]


___

# Матрицы и матричные операции. Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$  

$ det = \sin{x} \cdot \sin{x} - \cos{x} \cdot (-\cos{x}) = \sin^2{x}+\cos^2{x} = 1 $

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$ det = 4 \cdot 5 \cdot 9 = 180 $

In [20]:
a = np.array([4, 2, 3, 0, 5, 1, 0, 0, 9]).reshape(3, 3)
print(f'{np.linalg.det(a):.0f}')

180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$  

$ det = 1 \cdot 
\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2 \cdot 
\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3 \cdot 
\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = -3 - (-12) + 3(-3) = 0$

In [19]:
a = np.arange(1, 10).reshape(3, 3)
print(f'{np.linalg.det(a):.0f}')

-0


___

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
   
   $ det(AB) = detA \cdot detB \Rightarrow det(A^2) = det(A \cdot A) = detA \cdot detA = 4 \cdot 4 = 16 $

   б) $det(A^{T})$;  
   
   $detA^T = detA = 4 $

   в) $det(2A)$.
   
   Согласно свойству определителя, умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. Отсюда, если мы умножаем матрицу размерности $m$ на число $\lambda$, мы умножаем каждую строку/столбец на это число, а значит, мы умножаем итоговый определитель на число $\lambda$, $m$ раз.  
   
   $ |\lambda A| = \lambda^m|A| $  
   
   Или, в нашем случае  
   
   $ |2A| = 2^m\cdot4 = 2^{m+2} $

___

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

$ det = -2 \cdot 
\begin{vmatrix}
-14 & 6\\ 
7 & 13
\end{vmatrix} - 7 \cdot 
\begin{vmatrix}
4 & 6\\ 
-3 & 13
\end{vmatrix} + (-3) \cdot 
\begin{vmatrix}
4 & -14\\ 
-3 & 7
\end{vmatrix} = 448 - 490 + 42 = 0$

In [22]:
a = np.array([-2, 7, -3, 4, -14, 6, -3, 7, 13]).reshape(3, 3)
print(f'{np.linalg.det(a):.0f}')

0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$  

Третья строка может быть представлена, как сумма первых двух строк, поэтому отбросим ее

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix}$  

Видим, что определитель любого минора 2го порядка не равен 0, а значит ранг исходной матрицы равен 2

In [33]:
a = np.array([1, 2, 3, 1, 1, 1, 2, 3, 4]).reshape(3, 3)
np.linalg.matrix_rank(a)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Сначала проверим, есть ли отличный от нуля определитель у исходной матрицы. Разложим по первому столбцу

$det = 2 \cdot 
\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
0 & 4 & 3\\ 
\end{pmatrix} = 0$  

Видим, что максимальный ранг матрицы меньше 4  

Найдем ранг определитель минора 3го порядка, например  

$det = \begin{pmatrix}
0 & 2 & 2\\ 
0 & 4 & 3\\ 
3 & 5 & 6
\end{pmatrix} = 3 \cdot 
\begin{pmatrix}
2 & 2\\ 
4 & 3\\ 
\end{pmatrix} = -6 \neq 0$  

Следовательно ранг матрицы равен 3

In [39]:
a = np.array([0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 4, 3, 2, 3, 5, 6]).reshape(4, 4)
np.linalg.matrix_rank(a)

3