In [1]:
import numpy as np
import scipy
import scipy.linalg

# Системы линейных уравнений. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из 2й строки удвоенную первую

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$  

Теперь из 3й первую  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$  

Получим систему уравнений вида  

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4
\end{cases}$$

Пусть $x_4 = c$. Тогда  

$x_3 = \frac{3c-4}{2}$  
$x_2 = \frac{3c-4}{2}+5c+2$  
$x_1 = \frac{3c-4}{2}+2c-(\frac{3c-4}{2}+5c+2) = -3c-2 $  

___

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    

In [2]:
a = np.array([3, -1, 1, 2, -5, -3, 1, 1, -1]).reshape(3, 3)
b = np.array([4, -17, 0]).reshape(3, 1)
c = np.concatenate((a, b), axis=1)
print(a, '\n')
print(c, '\n')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}, '
      f'Ранг расширенной матрицы: {np.linalg.matrix_rank(c)}, '
      f'Количество переменных: {a.shape[1]}')

[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]] 

[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]] 

Ранг матрицы: 3, Ранг расширенной матрицы: 3, Количество переменных: 3


По теореме Кроникера-Капелли система совместна и имеет единственное решение

___

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    

In [3]:
a = np.array([2, -4, 6, 1, -2, 3, 3, -6, 9]).reshape(3, 3)
b = np.array([1, -2, 5]).reshape(3, 1)
c = np.concatenate((a, b), axis=1)
print(a, '\n')
print(c, '\n')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}, '
      f'Ранг расширенной матрицы: {np.linalg.matrix_rank(c)}, '
      f'Количество переменных: {a.shape[1]}')

[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]] 

[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]] 

Ранг матрицы: 1, Ранг расширенной матрицы: 2, Количество переменных: 3


По теореме Кроникера-Капелли система несовместна

___

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [4]:
a = np.array([1, 2, 5, 3, 1, -8]).reshape(2, 3)
b = np.array([4, -2]).reshape(2, 1)
c = np.concatenate((a, b), axis=1)
print(a, '\n')
print(c, '\n')
print(f'Ранг матрицы: {np.linalg.matrix_rank(a)}, '
      f'Ранг расширенной матрицы: {np.linalg.matrix_rank(c)}, '
      f'Количество переменных: {a.shape[1]}')

[[ 1  2  5]
 [ 3  1 -8]] 

[[ 1  2  5  4]
 [ 3  1 -8 -2]] 

Ранг матрицы: 2, Ранг расширенной матрицы: 2, Количество переменных: 3


По теореме Кроникера-Капелли система совместна и имеет бесконечное множество решений

___

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [5]:
a = np.array([1, 3, -2, 4, 0, 5, 0, 1, 0, 0, 3, 0, 0, 0, 0, 2]).reshape(4, 4)
b = np.array([3, 2, 4, 1]).reshape(4, 1)
c = np.concatenate((a, b), axis=1)
print(a, '\n')
print(c, '\n')
print(f'Ранг матрицы:{np.linalg.matrix_rank(a)}, '
      f'Ранг расширенной матрицы: {np.linalg.matrix_rank(c)}, '
      f'Количество переменных: {a.shape[1]}')

[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]] 

[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]] 

Ранг матрицы:4, Ранг расширенной матрицы: 4, Количество переменных: 4


По теореме Кроникера-Капелли система совместна и имеет единственное решение

___

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Вычтем из 2й строки удвоенную первую, из 3й строки утроенную первую

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
4 & 2 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a
\end{matrix}
\end{pmatrix}
$  

Теперь из 3й строки вычтем удвоенную вторую  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-3a-2(b-2a)
\end{matrix}
\end{pmatrix}
 = 
 \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
2 & 1 & 0\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-2a\\
c-2b+a
\end{matrix}
\end{pmatrix}$  

Отсюда можно сделать вывод, что при $c-2b+a \neq 0$ система несовместна

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    

In [6]:
a = np.array([1, -2, 3, -4]).reshape(2, 2)
b = np.array([1, 7]).reshape(2, 1)
x1 = np.around(np.linalg.det(np.concatenate((b, a[:, -1].reshape(2, 1)), 
                                            axis=1)) / np.linalg.det(a))
x2 = np.around(np.linalg.det(np.concatenate((a[:, 0].reshape(2, 1), b), 
                                            axis=1)) / np.linalg.det(a))
print(f'Значение x1: {x1}\nЗначение x2: {x2}')

Значение x1: 5.0
Значение x2: 2.0


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [7]:
a = np.array([2, -1, 5, 1, 1, -3, 2, 4, 1]).reshape(3, 3)
b = np.array([10, -2, 1]).reshape(3, 1)
x1 = np.around(np.linalg.det(np.concatenate((b, a[:, 1:]), 
                                            axis=1)) / np.linalg.det(a))
x2 = np.around(np.linalg.det(np.concatenate((a[:, :1], b, a[:, 2:]), 
                                            axis=1)) / np.linalg.det(a))
x3 = np.around(np.linalg.det(np.concatenate((a[:, :2], b,), 
                                            axis=1)) / np.linalg.det(a))
print(f'Значение x1: {x1}\nЗначение x2: {x2}\nЗначение x3: {x3}')

Значение x1: 2.0
Значение x2: -1.0
Значение x3: 1.0


___

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    

Получим матрицу U

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}\{стр_2 - 2стр_1\} \Rightarrow $  

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}\{стр_3 - 3стр_1\} \Rightarrow $  

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}\{стр_3 - 4стр_2\} \Rightarrow $  

$$ U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix} $$

Очевидно, что матрица L будет иметь вид  

$$ L = \begin{pmatrix}
1 & 0 & 0\\ 
2 & 1 & 0\\ 
3 & 4 & 1
\end{pmatrix} $$

In [16]:
l = np.array([1, 0, 0, 2, 1, 0, 3, 4, 1]).reshape(3, 3)
u = np.array([1, 2, 4, 0, 5, 4, 0, 0, 2]).reshape(3, 3)
l @ u

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

Получим матрицу U

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}\{стр_2 - 2стр_1\} \Rightarrow $  

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}\{стр_3 - 3стр_1\} \Rightarrow $  

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\  
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}\{стр_4 - 4стр_1\} \Rightarrow $  

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}\{стр_3 - 5стр_2\} \Rightarrow $  

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}\{стр_4 - 6стр_2\} \Rightarrow $  

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}\{стр_4 - 7стр_3\} \Rightarrow $  

$$ U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix} $$

Очевидно, что матрица L будет иметь вид  

$$ L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix} $$

In [17]:
l = np.array([1, 0, 0, 0, 2, 1, 0, 0, 3, 5, 1, 0, 4, 6, 7, 1]).reshape(4, 4)
u = np.array([1, 1, 2, 4, 0, 3, 4, 1, 0, 0, 3, 1, 0, 0, 0, 4]).reshape(4, 4)
l @ u

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

___

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица коэффициентов $A$ будет иметь вид  

$\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}$

Получим матрицу U

$\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}\{стр_2 - \frac{11}{2}стр_1\} \Rightarrow $  

$\begin{pmatrix}
2 & 1 & 3\\ 
0 & \frac{3}{2} & -\frac{23}{2}\\ 
9 & 8 & 4
\end{pmatrix}\{стр_3 - \frac{9}{2}стр_1\} \Rightarrow $  

$\begin{pmatrix}
2 & 1 & 3\\ 
0 & \frac{3}{2} & -\frac{23}{2}\\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}\{стр_3 - \frac{7}{3}стр_2\} \Rightarrow $  

$$ U = \begin{pmatrix}
2 & 1 & 3\\ 
0 & \frac{3}{2} & -\frac{23}{2}\\ 
0 & 0 & \frac{52}{3}
\end{pmatrix} $$

Очевидно, что матрица L будет иметь вид  

$$ L = \begin{pmatrix}
1 & 0 & 0\\ 
\frac{11}{2} & 1 & 0\\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix} $$

In [10]:
# проверим полученные матрицы
l = np.array([1, 0, 0, 11 / 2, 1, 0, 9 / 2, 7 / 3, 1]).reshape(3, 3)
u = np.array([2, 1, 3, 0, 3 / 2, -23 / 2, 0, 0, 52 / 3]).reshape(3, 3)
l @ u

array([[ 2.,  1.,  3.],
       [11.,  7.,  5.],
       [ 9.,  8.,  4.]])

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-\frac{23}{2},$$
$$y_{3}=\frac{52}{3}.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=-\frac{23}{2}, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$  

__Ответ:__ $x_1 = -1, x_2 = 0, x_3 = 1$

In [11]:
a = np.array([2, 1, 3, 11, 7, 5, 9, 8, 4]).reshape(3, 3)
b = np.array([1, -6, -5]).reshape(3, 1)
np.linalg.solve(a, b)

array([[-1.00000000e+00],
       [ 2.44249065e-16],
       [ 1.00000000e+00]])

___

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [12]:
a = np.array([81, -45, 45, -45, 50, -15, 45, -15, 38]).reshape(3, 3)
b = np.array([531, -460, 193]).reshape(3, 1)
c, low = scipy.linalg.cho_factor(a)
scipy.linalg.cho_solve((c, low), b)

array([[ 6.],
       [-5.],
       [-4.]])

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [21]:
class LUClass:
    def __init__(self, matrix):
        self.start_matrix = matrix
        n = matrix.shape[0]
        lu_mtx = np.zeros([n, n])
        for k in range(n):
            for j in range(k, n):
                lu_mtx[k, j] = self.start_matrix[k, j] - lu_mtx[k, :k] @ lu_mtx[:k, j]
            for i in range(k + 1, n):
                lu_mtx[i, k] = (self.start_matrix[i, k] - lu_mtx[i, :k] @ lu_mtx[:k, k]) / lu_mtx[k, k]
        self.lu_matrix = lu_mtx

    def l_matrix(self):
        l_mtx = self.lu_matrix.copy()
        for i in range(l_mtx.shape[0]):
            for j in range(l_mtx.shape[0]):
                if i == j:
                    l_mtx[i, j] = 1
                elif i < j:
                    l_mtx[i, j] = 0
        return l_mtx

    def u_matrix(self):
        u_mtx = self.lu_matrix.copy()
        for i in range(u_mtx.shape[0]):
            for j in range(u_mtx.shape[0]):
                if i > j:
                    u_mtx[i, j] = 0
        return u_mtx


new_lu = LUClass(np.array([1, 1, 2, 4, 2, 5, 8, 9, 
                           3, 18, 29, 18, 4, 22, 53, 33]).reshape(4, 4))
print(new_lu.start_matrix)
print(new_lu.lu_matrix)
print(new_lu.l_matrix())
print(new_lu.u_matrix())
print(new_lu.l_matrix() @ new_lu.u_matrix())

[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
[[1. 1. 2. 4.]
 [2. 3. 4. 1.]
 [3. 5. 3. 1.]
 [4. 6. 7. 4.]]
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]
[[1. 1. 2. 4.]
 [0. 3. 4. 1.]
 [0. 0. 3. 1.]
 [0. 0. 0. 4.]]
[[ 1.  1.  2.  4.]
 [ 2.  5.  8.  9.]
 [ 3. 18. 29. 18.]
 [ 4. 22. 53. 33.]]
